export type Lesson = {id:string;title:string;topic:string;minutes:number;intro:string;points:string[];code:string;output:string;exercise:string};
export const topics = [
{id:'dsa',title:'Data Structures & Algorithms',short:'DSA',symbol:'{ }',color:'green',description:'Build your problem-solving foundation.'},
{id:'web',title:'Web Development',short:'Web Development',symbol:'</>',color:'blue',description:'Create responsive websites and applications.'},
{id:'python',title:'Python',short:'Python',symbol:'Py',color:'purple',description:'Start simple. Automate something useful.'},
{id:'javascript',title:'JavaScript',short:'JavaScript',symbol:'JS',color:'yellow',description:'Bring your ideas to life in the browser.'},
{id:'database',title:'Databases & SQL',short:'SQL',symbol:'SQL',color:'orange',description:'Organize, query, and understand your data.'},
{id:'cs',title:'Computer Science',short:'CS Subjects',symbol:'01',color:'teal',description:'Understand what happens behind the code.'},
{id:'java',title:'Java',short:'Java',symbol:'J',color:'pink',description:'Learn the essentials of object-oriented code.'},
{id:'ai',title:'AI & Data Science',short:'AI & Data Science',symbol:'AI',color:'indigo',description:'Explore data and your first learning models.'}
];
export const lessons:Lesson[] = [
{id:'arrays',title:'Arrays: your first data structure',topic:'dsa',minutes:6,intro:'An array stores an ordered collection of values. Each value has a numbered position called an index. In JavaScript, the first index is 0.',points:['Create an array with square brackets. Related values, such as student marks, belong together.','Read or update one value with its index. marks[1] refers to the second mark.','Use length for the number of items and a loop to visit each item. Indexed access is O(1); visiting every item is O(n).'],code:'const marks = [72, 85, 91];\nmarks[0] = 75;\nfor (const mark of marks) {\n  console.log(mark);\n}',output:'75\n85\n91',exercise:'Create an array containing five marks. Calculate their total and divide by the array length to find the mean.'},
{id:'binary-search',title:'Binary search, step by step',topic:'dsa',minutes:8,intro:'Binary search finds a target in a sorted array by repeatedly halving the search range. Sorting is a requirement, not an optional optimization.',points:['Start with left at 0 and right at the final index.','Compare the middle value with the target. Search the right half if the middle is too small; otherwise search the left half.','Stop when the value is found or left passes right. Time complexity is O(log n) and iterative auxiliary space is O(1).'],code:'function search(a, target) {\n  let left = 0, right = a.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (a[mid] === target) return mid;\n    if (a[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}\nconsole.log(search([2, 5, 8, 12, 16], 12));',output:'3',exercise:'Trace the search for 7 in [1, 3, 5, 7, 9, 11]. Write down left, right, and mid at each step.'},
{id:'stacks',title:'Stacks and queues',topic:'dsa',minutes:7,intro:'Stacks and queues both hold collections, but remove elements in different orders. Choose the order that matches the problem.',points:['A stack is last in, first out (LIFO), like a pile of plates. Use push and pop for a JavaScript array stack.','A queue is first in, first out (FIFO), like students waiting at the canteen.','Undo histories use stacks. Task scheduling often uses queues. Array shift is O(n), so large queues should use a head index or linked structure.'],code:'const history = [];\nhistory.push("Type a word");\nhistory.push("Make it bold");\nconsole.log(history.pop());\nconsole.log(history.pop());',output:'Make it bold\nType a word',exercise:'Explain which data structure fits a printer processing documents in arrival order, and why.'},
{id:'complexity',title:'Understanding time complexity',topic:'dsa',minutes:6,intro:'Time complexity describes how the amount of work grows as the input size grows. Big O describes a growth bound rather than an exact time in seconds.',points:['O(1): a fixed amount of work, such as reading an array element by index.','O(n): work grows linearly, such as adding all n marks.','O(n²): two full nested passes over n items. For large inputs this becomes expensive. Ignore constant factors when describing growth.'],code:'function total(values) {\n  let sum = 0;\n  for (const value of values) sum += value;\n  return sum;\n}\nconsole.log(total([10, 20, 30]));',output:'60',exercise:'If an algorithm compares every pair in a list, how does its work roughly change when the list size doubles?'},
{id:'html',title:'HTML: structure your first page',topic:'web',minutes:7,intro:'HTML gives a web page its structure and meaning. Elements identify headings, paragraphs, links, images, and forms.',points:['Start with a document type, html, head, and body. The head contains metadata; the body contains visible content.','Use one main heading and a logical heading order. Semantic elements such as main and nav describe the purpose of content.','A link needs an href. Form inputs need associated labels so keyboard and assistive technology users can understand them.'],code:'<!doctype html>\n<html lang="en">\n<head><title>My school</title></head>\n<body>\n  <main>\n    <h1>Welcome to our school</h1>\n    <p>Learn something new today.</p>\n    <a href="/courses">Explore courses</a>\n  </main>\n</body>\n</html>',output:'A page with a heading, paragraph, and course link.',exercise:'Write a page about your school with a heading, two paragraphs, and a list of three subjects.'},
{id:'css',title:'CSS layouts with Flexbox',topic:'web',minutes:8,intro:'CSS controls presentation. Flexbox arranges items along one main axis and helps distribute available space.',points:['Set display: flex on the parent. Its direct children become flex items.','gap creates space between items. justify-content distributes items along the main axis; align-items aligns them on the cross axis.','Use flex-wrap: wrap so items can move to another line. Avoid fixed widths that overflow a small phone screen.'],code:'.cards {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 16px;\n  align-items: stretch;\n}\n.card {\n  flex: 1 1 240px;\n  padding: 24px;\n  border: 1px solid #ddd;\n}',output:'Cards share the row and wrap when there is not enough space.',exercise:'Create three subject cards. Make them appear in one row on a large screen and wrap on a small screen.'},
{id:'http',title:'How the web works: HTTP',topic:'web',minutes:6,intro:'A browser communicates with a server using requests and responses. HTTP defines the structure and meaning of those messages.',points:['A request includes a method and a path. GET retrieves data; POST commonly submits a change.','A response includes a status code. 200 means success, 404 means not found, and 500 indicates a server error.','HTTPS encrypts traffic in transit. Never send passwords through plain HTTP in a production application.'],code:'async function loadCourses() {\n  const response = await fetch("/api/courses");\n  if (!response.ok) throw new Error("Could not load courses");\n  return response.json();\n}',output:'With a working /api/courses endpoint, the function returns its JSON response.',exercise:'Describe the request and response involved when a student opens a course page.'},
{id:'js-variables',title:'JavaScript variables and types',topic:'javascript',minutes:6,intro:'A variable gives a name to a value. JavaScript values include numbers, strings, booleans, arrays, objects, null, and undefined.',points:['Use const when you do not need to reassign the binding. Use let when reassignment is needed.','A const object can still have its properties changed. const prevents replacing the binding, not changing every nested value.','Use typeof to inspect a basic type. Addition with a string can concatenate text: 2 + "3" produces "23".'],code:'const student = "Aline";\nlet mark = 75;\nmark += 5;\nconst passed = mark >= 50;\nconsole.log(student, mark, passed);\nconsole.log(typeof mark);',output:'Aline 80 true\nnumber',exercise:'Store a student name and three marks. Calculate the average and a boolean showing whether it is at least 50.'},
{id:'js-functions',title:'Functions and return values',topic:'javascript',minutes:7,intro:'A function packages a reusable task. Parameters receive inputs, and return sends a result back to the caller.',points:['Define the task once, then call it with different arguments.','return exits the function immediately. A function without an explicit returned value returns undefined.','An arrow function provides another syntax. A concise expression body returns its expression automatically.'],code:'function average(a, b) {\n  return (a + b) / 2;\n}\nconst double = value => value * 2;\nconsole.log(average(70, 90));\nconsole.log(double(6));',output:'80\n12',exercise:'Write a function area(width, height) that returns the area of a rectangle. Call it with 8 and 5.'},
{id:'js-arrays',title:'Transform arrays with map and filter',topic:'javascript',minutes:8,intro:'map transforms each item into a new item. filter keeps items that pass a condition. Both return new arrays.',points:['map preserves the number of elements and is useful for converting or formatting data.','filter can produce fewer elements. Its callback should return a truthy value for items to keep.','Neither method directly changes the original array, but mutating referenced objects inside callbacks can still affect shared objects.'],code:'const marks = [40, 75, 90, 32];\nconst passed = marks.filter(mark => mark >= 50);\nconst adjusted = marks.map(mark => mark + 5);\nconsole.log(passed);\nconsole.log(adjusted);',output:'[75, 90]\n[45, 80, 95, 37]',exercise:'Given prices [100, 200, 500], use map to apply a 10% discount and filter to keep prices below 200.'},
{id:'python-basics',title:'Python variables and input',topic:'python',minutes:6,intro:'Python uses names to refer to values and indentation to group statements. You can start with calculations and simple printed output.',points:['Assign a value using =. Python infers the type from the value.','input returns a string. Use int or float when a numeric calculation is required.','Indent nested statements consistently, conventionally with four spaces. Mixing indentation can cause an error.'],code:'name = "Aline"\nmark = 82\nprint(f"{name} scored {mark}")\nif mark >= 50:\n    print("Passed")',output:'Aline scored 82\nPassed',exercise:'Ask for two numbers, convert them with float, and print their sum. Run the example in a Python environment.'},
{id:'python-loops',title:'Python lists and loops',topic:'python',minutes:7,intro:'A Python list stores ordered values. A for loop visits each value so you can perform a repeated task.',points:['List indices start at zero. A negative index such as -1 accesses from the end.','Use for value in values to visit items directly. range(3) produces 0, 1, and 2.','Use append to add an item. List comprehensions can create transformed lists in a readable expression.'],code:'marks = [60, 80, 100]\nfor mark in marks:\n    print(mark)\nprint(sum(marks) / len(marks))',output:'60\n80\n100\n80.0',exercise:'Create a list of five numbers. Print only the even numbers using a for loop and an if statement.'},
{id:'sql-select',title:'SQL: select and filter records',topic:'database',minutes:7,intro:'SQL is used to work with relational databases. A table organizes records into rows with named columns.',points:['SELECT specifies the columns to retrieve. FROM identifies the table.','WHERE filters rows. ORDER BY controls sorting; descending order uses DESC.','Use parameterized queries for user input. Building query strings by concatenating input can lead to SQL injection.'],code:'-- Suppose students contains Aline (82), Eric (45), and Neza (90).\nSELECT name, mark\nFROM students\nWHERE mark >= 50\nORDER BY mark DESC;',output:'Neza | 90\nAline | 82',exercise:'Write a query to return the names of students with marks between 60 and 80, inclusive.'},
{id:'sql-joins',title:'Connect tables using JOIN',topic:'database',minutes:8,intro:'A join combines related records from two tables. Relationships are commonly expressed using a primary key and a foreign key.',points:['An INNER JOIN returns matching records from both tables.','A LEFT JOIN keeps every row from the left table and fills unmatched right-side columns with NULL.','State the matching condition with ON. A missing or incorrect condition can multiply rows unexpectedly.'],code:'SELECT students.name, classes.title\nFROM students\nINNER JOIN classes\n  ON students.class_id = classes.id;',output:'Each matching student is shown alongside their class title.',exercise:'Which join would list all classes, including classes that have no enrolled students?'},
{id:'networks',title:'Computer networks: the essentials',topic:'cs',minutes:7,intro:'A network allows devices to exchange data. A school LAN connects nearby devices, while the internet connects networks across the world.',points:['An IP address identifies an interface for network communication. DNS resolves names to records such as IP addresses.','A switch connects devices within a local network. A router forwards packets between networks.','Bandwidth describes capacity. Latency describes delay. A high-capacity connection can still have noticeable delay.'],code:'Example journey:\nBrowser → DNS lookup → destination IP\nBrowser → local router → internet → web server\nWeb server → response → browser',output:'The browser receives the resources needed to display the page.',exercise:'Explain why a computer may connect to the school Wi-Fi but still fail to open an internet website.'},
{id:'os',title:'Processes, threads, and memory',topic:'cs',minutes:8,intro:'An operating system manages resources and provides services for applications. It schedules work, manages memory, and controls access to devices.',points:['A process is an executing program with its own address space.','Threads within a process share memory, making communication easier but requiring care with concurrent updates.','Virtual memory gives each process an address-space abstraction. A memory leak occurs when no-longer-needed allocations remain retained.'],code:'Process: web browser\n  Thread: interface work\n  Thread: background work\n\nThe operating system schedules runnable threads.',output:'Several tasks can make progress while the operating system coordinates resources.',exercise:'Why can a shared counter give an incorrect result when two threads update it without synchronization?'},
{id:'java-basics',title:'Your first Java program',topic:'java',minutes:7,intro:'Java is a statically typed language. A typical entry point is the main method in a class.',points:['Declare the type of a variable, such as int, double, or String.','Use System.out.println to print a line. Java statements commonly end with semicolons.','The public class name should match the source filename. Compile Main.java and run Main in a Java environment.'],code:'public class Main {\n  public static void main(String[] args) {\n    String name = "Aline";\n    int mark = 82;\n    System.out.println(name + ": " + mark);\n  }\n}',output:'Aline: 82',exercise:'Modify the program to print the average of three marks as a decimal number.'},
{id:'java-objects',title:'Classes and objects in Java',topic:'java',minutes:8,intro:'A class describes data and behavior. An object is an instance of that class with its own state.',points:['Fields hold state. Methods describe behavior. A constructor initializes an object.','Use new to create an instance. Different instances can have different field values.','Encapsulation restricts direct access to implementation details, often through private fields and public methods.'],code:'class Student {\n  private String name;\n  Student(String name) { this.name = name; }\n  String greet() { return "Hello, " + name; }\n}\n// Inside a main method:\nStudent s = new Student("Aline");\nSystem.out.println(s.greet());',output:'Hello, Aline',exercise:'Create a Rectangle class with width and height fields and a method that returns its area.'},
{id:'data-analysis',title:'Start thinking with data',topic:'ai',minutes:7,intro:'Data analysis turns observations into useful answers. Start with a clear question before choosing a chart or calculating a statistic.',points:['Inspect missing values, duplicate records, and units before calculating results.','The mean is the sum divided by the number of observations. The median is the middle value after sorting and is less sensitive to extreme values.','Correlation describes association. It does not by itself establish that one variable causes another.'],code:'marks = [40, 60, 70, 80, 100]\nmean = sum(marks) / len(marks)\nmedian = sorted(marks)[len(marks) // 2]  # odd-length example\nprint(mean, median)',output:'70.0 70',exercise:'Calculate the mean and median of [10, 12, 13, 15, 100]. Which better describes a typical value here?'},
{id:'machine-learning',title:'Machine learning: train and evaluate',topic:'ai',minutes:8,intro:'Machine learning fits patterns from examples so a model can make predictions for new inputs. Evaluation tests whether those patterns generalize.',points:['Supervised learning uses labeled examples. Classification predicts categories; regression predicts numerical values.','Split data into training and evaluation sets. Prevent information from the evaluation set leaking into training.','Overfitting means performing well on training examples but poorly on new examples. Compare against a simple baseline before using a complex model.'],code:'Question: Will a student pass?\nFeatures: attendance, practice scores\nLabel: passed / did not pass\n\n1. Train using past labeled examples.\n2. Predict on a separate evaluation set.\n3. Compare predictions with actual outcomes.',output:'A measured estimate of how well the model works on unseen examples.',exercise:'Is predicting a house price a classification or regression problem? Explain your answer.'}
];
export const courses=[
{id:'dsa-foundations',title:'DSA Foundations',subtitle:'Think clearly. Solve with confidence.',topic:'dsa',level:'Beginner',lessons:['arrays','complexity','binary-search','stacks'],color:'green'},
{id:'web-foundations',title:'Full Stack Foundations',subtitle:'From your first page to web requests.',topic:'web',level:'Beginner',lessons:['html','css','js-variables','js-functions','js-arrays','http','sql-select','sql-joins'],color:'blue'},
{id:'python-data',title:'Python & Data Essentials',subtitle:'Turn your first lines into useful insights.',topic:'python',level:'Beginner',lessons:['python-basics','python-loops','data-analysis','machine-learning'],color:'purple'},
{id:'java-foundations',title:'Java Programming',subtitle:'Build a strong programming foundation.',topic:'java',level:'Beginner',lessons:['java-basics','java-objects','complexity','os'],color:'orange'}
];
export const problems=[
{id:'array-sum',title:'Sum of an array',topic:'Arrays',difficulty:'Easy',description:'Return the sum of all numbers in the input array. An empty array has a sum of 0.',starter:'function solve(nums) {\n  // Return the sum of nums\n  return 0;\n}',example:'Input: [2, 4, 6]\nOutput: 12',tests:[{input:[2,4,6],expected:12},{input:[],expected:0},{input:[-3,8,-2],expected:3},{input:[0],expected:0}],hint:'Keep a running total as you visit each number.',solution:'function solve(nums) {\n  return nums.reduce((sum, n) => sum + n, 0);\n}'},
{id:'palindrome',title:'Palindrome check',topic:'Strings',difficulty:'Easy',description:'Return true if the input string reads the same forward and backward. Compare characters exactly; case and spaces matter.',starter:'function solve(text) {\n  return false;\n}',example:'Input: "radar"\nOutput: true',tests:[{input:'radar',expected:true},{input:'hello',expected:false},{input:'',expected:true},{input:'Aa',expected:false}],hint:'Compare characters from opposite ends, or reverse the string.',solution:'function solve(text) {\n  return text === [...text].reverse().join("");\n}'},
{id:'largest',title:'Find the largest element',topic:'Arrays',difficulty:'Easy',description:'Return the largest number in a non-empty array. The array has at most 1,000 elements.',starter:'function solve(nums) {\n  return nums[0];\n}',example:'Input: [3, 9, 2, 7]\nOutput: 9',tests:[{input:[3,9,2,7],expected:9},{input:[-9,-2,-4],expected:-2},{input:[5],expected:5},{input:[0,0],expected:0}],hint:'Start with the first value and update the maximum when a larger one appears.',solution:'function solve(nums) {\n  let largest = nums[0];\n  for (const n of nums) if (n > largest) largest = n;\n  return largest;\n}'},
{id:'reverse',title:'Reverse a string',topic:'Strings',difficulty:'Easy',description:'Return the characters of the input ASCII string in reverse order.',starter:'function solve(text) {\n  return text;\n}',example:'Input: "code"\nOutput: "edoc"',tests:[{input:'code',expected:'edoc'},{input:'',expected:''},{input:'hello world',expected:'dlrow olleh'},{input:'a',expected:'a'}],hint:'Convert the string to an array, reverse it, and join it.',solution:'function solve(text) {\n  return text.split("").reverse().join("");\n}'},
{id:'unique',title:'Remove duplicates',topic:'Arrays',difficulty:'Easy',description:'Return an array with repeated numbers removed, preserving the order of their first appearance.',starter:'function solve(nums) {\n  return nums;\n}',example:'Input: [2, 1, 2, 3, 1]\nOutput: [2, 1, 3]',tests:[{input:[2,1,2,3,1],expected:[2,1,3]},{input:[],expected:[]},{input:[7,7,7],expected:[7]},{input:[-1,0,-1],expected:[-1,0]}],hint:'A Set stores unique values in insertion order.',solution:'function solve(nums) {\n  return [...new Set(nums)];\n}'},
{id:'balanced',title:'Balanced parentheses',topic:'Stacks',difficulty:'Medium',description:'Given a string containing only ( and ), return true if every opening parenthesis has a matching closing parenthesis in the correct order.',starter:'function solve(text) {\n  return false;\n}',example:'Input: "(()())"\nOutput: true',tests:[{input:'(()())',expected:true},{input:')(',expected:false},{input:'(()',expected:false},{input:'',expected:true},{input:'()()',expected:true}],hint:'Track the count of open parentheses. It must never become negative and must end at zero.',solution:'function solve(text) {\n  let balance = 0;\n  for (const c of text) {\n    balance += c === "(" ? 1 : -1;\n    if (balance < 0) return false;\n  }\n  return balance === 0;\n}'},
{id:'two-sum',title:'Two sum',topic:'Hash Maps',difficulty:'Medium',description:'The input has nums and target. Return the two indices in ascending order whose values sum to target, or [] if no pair exists. At most one valid pair exists. Do not reuse an element.',starter:'function solve({ nums, target }) {\n  return [];\n}',example:'Input: {"nums":[2,7,11,15],"target":9}\nOutput: [0,1]',tests:[{input:{nums:[2,7,11,15],target:9},expected:[0,1]},{input:{nums:[3,3],target:6},expected:[0,1]},{input:{nums:[1,2],target:8},expected:[]},{input:{nums:[3,2,4],target:6},expected:[1,2]}],hint:'Store each seen number and its index in a Map. Look for target minus the current value.',solution:'function solve({ nums, target }) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    if (seen.has(target - nums[i])) return [seen.get(target - nums[i]), i];\n    seen.set(nums[i], i);\n  }\n  return [];\n}'},
{id:'binary-search',title:'Search a sorted array',topic:'Binary Search',difficulty:'Medium',description:'The input has a sorted array nums containing distinct numbers and a target. Return the index of target, or -1 if absent. Aim for O(log n) time.',starter:'function solve({ nums, target }) {\n  return -1;\n}',example:'Input: {"nums":[1,3,5,7],"target":5}\nOutput: 2',tests:[{input:{nums:[1,3,5,7],target:5},expected:2},{input:{nums:[],target:3},expected:-1},{input:{nums:[2],target:2},expected:0},{input:{nums:[1,4,8],target:6},expected:-1}],hint:'Move left or right past the middle index after each unsuccessful comparison.',solution:'function solve({ nums, target }) {\n  let left = 0, right = nums.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (nums[mid] === target) return mid;\n    if (nums[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}'}
];
export const questions=[
{q:'Which data structure uses last in, first out?',options:['Queue','Stack','Sorted array','Hash map'],answer:1,explanation:'A stack removes the most recently added item first.'},
{q:'What is required before using binary search on an array?',options:['The array must be sorted','All values must be positive','It must have an even length','It must contain strings'],answer:0,explanation:'Binary search uses sorted order to decide which half to discard.'},
{q:'What does JavaScript map return?',options:['Only the first item','The original array length','A new array of transformed items','A boolean'],answer:2,explanation:'map applies a callback to each item and returns the transformed values in a new array.'},
{q:'Which SQL clause filters rows?',options:['ORDER BY','FROM','SELECT','WHERE'],answer:3,explanation:'WHERE keeps rows satisfying a condition; ORDER BY sorts results.'},
{q:'What is the time complexity of one complete pass through n items?',options:['O(1)','O(n)','O(log n)','O(n²)'],answer:1,explanation:'If each item takes constant work, n items require linear work.'},
{q:'What does HTTP status 404 normally mean?',options:['Request succeeded','Authentication succeeded','Resource not found','Server is starting'],answer:2,explanation:'404 indicates that the requested resource was not found.'},
{q:'What does Python input() return?',options:['A string','Always an integer','A list','A boolean'],answer:0,explanation:'input returns text. Convert it with int or float when you need a number.'},
{q:'Why evaluate a model on data separate from its training data?',options:['To guarantee perfect accuracy','To make the file smaller','To remove every error','To estimate performance on unseen examples'],answer:3,explanation:'A separate evaluation set helps reveal whether the model generalizes beyond training examples.'}
];
